// <auto-generated />
using System;
using BugTracker.Storage.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BugTracker.Storage.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BugTracker.Storage.Model.PersistenceEntityChange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("EntityId");

                    b.Property<long>("EntityType");

                    b.Property<string>("ModifiedValue");

                    b.Property<string>("OriginalValue");

                    b.Property<long>("PerformedOperationId");

                    b.Property<string>("Property")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("PerformedOperationId");

                    b.ToTable("EntityChange","Audit");
                });

            modelBuilder.Entity("BugTracker.Storage.Model.PersistenceIssue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("Issue","Issues");
                });

            modelBuilder.Entity("BugTracker.Storage.Model.PersistencePerformedOperation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("OperationId");

                    b.Property<DateTime>("PerformedOn");

                    b.HasKey("Id");

                    b.ToTable("PerformedOperation","Audit");
                });

            modelBuilder.Entity("BugTracker.Storage.Model.PersistenceEntityChange", b =>
                {
                    b.HasOne("BugTracker.Storage.Model.PersistencePerformedOperation")
                        .WithMany("EntityChanges")
                        .HasForeignKey("PerformedOperationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
